### ISSUE TITLE
Add a minimap

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#10]
Adding a simple minimap of the whole map so you can see other players might be helpful in a way

![image](https://user-images.githubusercontent.com/58097612/196191692-6ddaa7f1-81fd-4194-89bc-2af61008c750.png)

**Comment by 3kh0** [comment]
I should also state that the minimap does not have to be dynamic (meaning that it moves with the players) it can be still, displaying the whole map with the players

**Comment by eliasku** [comment]
quick concept :)
<img width="1146" alt="minimap1" src="https://user-images.githubusercontent.com/3038174/198893251-acaddb70-5fae-439c-aaa7-138072801f3b.png">

**Comment by 3kh0** [comment]
Looks great! I did notice when there are tons of items it lags the server bad, Link to #5

**Comment by eliasku** [comment]
additional object size in mini-map 
![image](https://user-images.githubusercontent.com/3038174/199344079-5140b3af-e360-41b9-9d90-1b165d634b2d.png)
