### ISSUE TITLE
Reload mechanics

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#11]
I made this since I saw it in the `post.md` file, and I wanted to make up some numbers for ammo capacity since I have played my fair share of CSGO. I added the number of rounds in each mag, the gun in CSGO it is after. I also think the user should start out with 3 mags of each. You can find ammo in the barrels, boxes, and tombstones. Picking up one thing of ammo (💊 can be used as the icon) will grant you one more mag of ammo for your current weapon (30 more bullets for the machine gun, 7 more for the pistol, etc). Having more than 1 type would get confusing.

Example bullet info on the HUD: `🖊 30/90` this would be right where is displays the weapon you are currently holding

🔫 Pistol **7** desert eagle
🖊 Machine-gun **30** ak
️✏️ Heavy machine-gun **30** m1a4
🪥 Shotgun **7** XM shotgun
⛏ Crossbow **20** scar-20
🔌 Plasma-gun **35** m1a4s
🧵 Rail-gun **1** awp

**Comment by 3kh0** [comment]
The times of the reload time should also be taken from CSGO, since it is balanced

**Comment by eliasku** [comment]
I add initial mag reloading concept, but with infinite ammo currently

**Comment by 3kh0** [comment]
I like the idea of that. Since the pen is overpowered with no reload

**Comment by eliasku** [comment]
I think new [R] - reload button would be nice! If you are noob you will lose all your magazines in case you do expensive early reloads. It depends on your decision to be ready or safe ammo magazines :)

**Comment by eliasku** [comment]
Reload button added as well
