### ISSUE TITLE
Off-hand slot

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#13]
This would be shown on the HUD, you can swap by using scroll, or pressing `1` and `2` on your keyboard.

`🔫 | 🖊 30/90`

**Comment by eliasku** [comment]
Initial prototype on master press [Q] to swap primary/secondary slot.

I think [E] (DROP) button should also PICK the weapon (like in Nuclear Throne). Auto pick-up weapon only if you have 1st or 2nd weapon slot empty. WDYT?

**Comment by 3kh0** [comment]
Yes E should also pick the weapon, since it is kinda hard to pick up certain weapons, you have to drop the item and make sure you don't walk over any other weapons

**Comment by 3kh0** [comment]
Much better, I will link to #22 because some people might not know how to switch
