### ISSUE TITLE
Cp question

### ISSUE THREAD

**Issue by QARX6994** [eliasku/13#154]
What are the cp for? Is there a shop? If not, add one pls.

**Comment by eliasku** [comment]
Hi, nice to meet you! No, I plan to add leveling screen https://github.com/eliasku/13/issues/35 and shop to spend credits. If you have suggestions what kind of stuff credits could be spent for, please let me know! It will be relly helpful :)

**Comment by QARX6994** [comment]
Thank you! I really admire this game and play it soooo much, probably put like 10 hours in to it. I hope we can work together because I am new to coding. :)
Thanks for the reply!
