### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by QARX6994** [eliasku/13#156]
Whenever I try to join a game with people I  it, I can’t. It loads, and then kicks me back to the menu screen. Pls fix.

**Comment by eliasku** [comment]
We had 2 issues there: https://github.com/eliasku/13/issues/6 and https://github.com/eliasku/13/issues/128
Unfortunately current model is simple peer to peer topology (each user to each user), and it's hard to say, is it code issue or network between 2 peers can't establish connection. This thing is not easy to fix right now.

**Comment by eliasku** [comment]
@QARX6994 please send me direct message in https://twitter.com/eliaskuvoice or somewhere else, so we will try play-testing session via the network together

**Comment by QARX6994** [comment]
I have discord, no Twitter. I don’t use Twitter.

**Comment by eliasku** [comment]
@QARX6994 discord eliasku#0166

**Comment by QARX6994** [comment]
Sent the friend request
