### ISSUE TITLE
Reset kills on death

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#18]
When you die, your kills get reset

**Comment by eliasku** [comment]
Current death-match mode should not reset FRAGS, because in PvP mode players kills each other, the leader is who make more scores, not matters how many times he died

**Comment by 3kh0** [comment]
I was also referring to a popular game called shell shockers, and when you die, the kills get reset. It would also be nice if there was a set game duration like 5 minutes, then the kills, and everything gets reset.

**Comment by eliasku** [comment]
Thanks! I think I got the idea

**Comment by eliasku** [comment]
I make frags reset on death, but all scores converted to credits balance :)
