### ISSUE TITLE
Running this on replit

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#2]
I want to run 13 on a popular hosting provider, replit. But I cant seem to do it.

I get a error when I run it with ts
![image](https://user-images.githubusercontent.com/58097612/195670836-b45dcc86-475c-4d02-b930-bc0fffa0ae51.png)

But when I use node.js it just gets stuck.

![image](https://user-images.githubusercontent.com/58097612/195672381-c3fc455d-51e1-41d6-8224-3c6a6dd448af.png)

**Comment by eliasku** [comment]
Nice service. I select Node.js target, then import GitHub project (prefer the latest master). To build I run in shell: 
1) `npm i`
2) `ts-node --esm tools/build.ts` - here you have to wait...
3) `npm start`

I'm going to disable RoadRoller step to improve build speed dramatically

**Comment by eliasku** [comment]
@3kh0 Now you could try `node.js` project the latest `master` with Shell commands:
```shell
npm i
npm run build
npm start
```

**Comment by 3kh0** [comment]
Thanks! It works now!
