### ISSUE TITLE
New loading screen

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#23]
I think that a redesign of the front page could be redesigned, here was a mock I made in a few minutes. The Username box would be a text field, and everytime the user clicks the play button it sets the local storage value to the value of that text box. the GitHub logo would be a hyperlink linking to this repo, and the text below would show how many people are playing right now. The same bloody background will still be there, just behind everything. This allows you to stay on the menu (if you really wanted) because it is super sensitive right now

![2022_11_02_0u4_Kleki](https://user-images.githubusercontent.com/58097612/199611882-9bf488fc-3d1d-494a-a2b4-a55c0e5cec5b.png)

**Comment by eliasku** [comment]
@3kh0 there is no more for global any-key-down event in Main Menu. Game will start only on [START] button click/tap event

**Comment by 3kh0** [comment]
@eliasku that does make it better, what about just the general update of the screen

**Comment by eliasku** [comment]
@3kh0 I agreed, the whole UI should be improved step by step, there is no general end-point design yet. I just made small efforts with ready-to-use functionality. What about the link, there is no github emoji, so I can't quickly add image to the button right now. Current solution also has an option to mimic git-tag style `🏷️ v1.0.2` WDYT? Actually I don't mind if you create minor look/func wishes to separated issues :) for example, I miss to add mouse-scroll support to switch weapon slots, but issue is closed already

**Comment by 3kh0** [comment]
you could add a tag emoji just to make it look nicer, but I think it will do for now
