### ISSUE TITLE
out of ammo

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#24]
It is not very clear when you run out of ammo, so it would be nice to have some red text that appears when you try to shoot without any ammo

![2022_11_02_0ub_Kleki](https://user-images.githubusercontent.com/58097612/199612415-1230ce27-f185-48fa-a2ca-8e1ac1da8838.png)

**Comment by eliasku** [comment]
I did something like floating text.. very similar to NT game

https://user-images.githubusercontent.com/3038174/199754191-630a6e38-e85d-4997-9326-dda8e9b8abae.mp4

**Comment by 3kh0** [comment]
I love it!
