### ISSUE TITLE
Fly jump glitch

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#3]
Using a pen and jumping, you can "fly" this makes you unable to hit people on the ground, but makes you invincible to others on the ground. While you fly, you can damage other players if they are flying through. First, get a pen, hold down space and your left mouse button. Do not release these buttons and you can fly.

This was me on the ground, and me on an alt, flying
[Screen recording 2022-10-13 16.06.52.webm](https://user-images.githubusercontent.com/58097612/195698802-b2e6c64d-44e2-4009-8620-9f97c4c7d6d3.webm)

Using a corner, you can also glitch into a wall. First you get a pen, go to one of the top corners, hold down space, w, and your left mouse button for about 20 seconds.

**Comment by 3kh0** [comment]
[Screen recording 2022-10-13 16.10.16.webm](https://user-images.githubusercontent.com/58097612/195699996-54bdb927-ba89-4685-9808-69ce10c05d6d.webm)

Second video of the wall hack

**Comment by 3kh0** [comment]
[Screen recording 2022-10-13 16.06.52.webm](https://user-images.githubusercontent.com/58097612/195700030-66038e5f-f6bc-4c44-9c6e-7dbd7035b2b8.webm)

First video of the fly hack

**Comment by eliasku** [comment]
@3kh0  please try the latest master. This happens because while you press JUMP button - gravity is actually less than normal to simulate long jump effect. So the fix: while weapon is triggering we KICK character back, so we need to  limit this effect only while character is on the ground

**Comment by 3kh0** [comment]
@eliasku This did fix it while I was testing it on grtc.herokuapp.com Could #4 also be a backup fix just in case?

**Comment by eliasku** [comment]
@3kh0 the PR is invalid, this function used in other places as well, and should affect velocity for `z != 0` as well. The correct fix is on grtc/ga13 already

**Comment by 3kh0** [comment]
Alright! Thanks!
