### ISSUE TITLE
Custom rooms

### ISSUE THREAD

**Issue by eliasku** [eliasku/13#38]
Add option to create room and share the link with friends. Custom room have various settings to create, for example: 
- Name
- Max Players limit
- NPC spawn rate and limit

Unblocks: 
- Co-op mode - players only fight versus NPC (to implement #39)
- Time-limit room option (to implement #49)

**Comment by 3kh0** [comment]
The link could be something like https://13game.lol/#gamecode shellshockers uses this url scheme aswell.
