### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#43]
I updated my copy with `git pull`, and it does not seem to work, this also happens on next13 as well

![image](https://user-images.githubusercontent.com/58097612/202917795-f32af32d-bb15-4645-877d-fca3013eec08.png)

**Comment by eliasku** [comment]
Whooops! Will fix soon, forgot to copy new font. Its only unreleased 1.0.7, you could use 1.0.6 tag  for stable. Thanks for the report!

**Comment by eliasku** [comment]
@3kh0  could you recheck? seems like https://next13.herokuapp.com/ is OK now. I noticed you have error about `e.ttf`, so I'm not sure you have right commands to build or start. Be sure you use the following: 
```
npm i
# this should make `public` folder for all public-hosted files (assets)
npm run build
# notice that `server.js` now build into the root of the project, to avoid serving server code from `public` folder
node server.js
```

**Comment by eliasku** [comment]
@3kh0 yes, I recheck my own replit, so I have to change couple of commands in config, then I successfully able to run the project.
![image](https://user-images.githubusercontent.com/3038174/202922177-ae0fc868-565a-493f-9e6b-f67b03478936.png)

Maybe I should commit besic replit configs into the repo? WDYT?
