### ISSUE TITLE
Remove items after set time

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#5]
The server can get really laggy due to the items, please make it so they can despawn after a minute or so.

**Comment by 3kh0** [comment]
[Screen recording 2022-10-17 15.23.41.webm](https://user-images.githubusercontent.com/58097612/196264732-4c714166-209a-44db-a0ae-edfffd38ec19.webm)

more footage of when you join

**Comment by eliasku** [comment]
Done, 10 seconds and simple blinking animation. One thing, if you out of ammo - there is no way to brake Graves or Barrels..

**Comment by 3kh0** [comment]
Works! Amazing!
