### ISSUE TITLE
Kid-mode blood

### ISSUE THREAD

**Issue by eliasku** [eliasku/13#51]
Just visually very colorful splats instead of RED blood. Addition to #48

**Comment by 3kh0** [comment]
It is not blood, it is just red kool aid!

**Comment by eliasku** [comment]
https://user-images.githubusercontent.com/3038174/204104400-d369715f-003f-4dec-b74a-a5d29d1658c6.mov

**Comment by 3kh0** [comment]
Good idea, linking back to the settings thing, you should have a option for chancing the amount of blood, like, 0%, 25%, 50%, 75% ,100% (default), 125%, 150%, 175%, 200%
