### ISSUE TITLE
Hard to join when there are other players

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#6]
When I try to join while others are in the game, I just get stuck on the start screen. I went to the endpoint and this is what I saw:

![image](https://user-images.githubusercontent.com/58097612/195922834-827dd69e-39d2-42b0-b01e-afde1cabc1bd.png)

I know that the names are the usernames of the players, `balls` and `berd`

**Comment by 3kh0** [comment]
This issue does seem to be fixed, on https://grtc.herokuapp.com/ I can join much better but on https://ga13.herokuapp.com/ it does not work, that might be because it has not been updated.

**Comment by eliasku** [comment]
@3kh0 I rework the join flow, so we need to check the case.
1. I hope joining the game, when first player deactivate the browser tab should works now.
2. The situation related to Firewalls and Networks, when you can't connect 2 specific peers via WebRTC is still there, but it's the different kind of issue, I created one https://github.com/eliasku/13/issues/128
