### ISSUE TITLE
Hide footprints after some time

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#68]
Make the footprints on the ground go away after say one minute, i made a patch of the ground solid black :)

**Comment by eliasku** [comment]
@3kh0 lol did you save a screenshot? I'm going to do slow fade with start map texture, it will affect also blood

**Comment by 3kh0** [comment]
Yeah I am on linux and I did a opss with the sudo rm command so unfortunately it is gone, but a slow fade would be nice, better ways to find a get someone with the fading of the foot prints

**Comment by eliasku** [comment]
![image](https://user-images.githubusercontent.com/3038174/206674944-35d39997-a67e-4902-b240-e9e8445186c5.png)
