### ISSUE TITLE
Keep join banner playing

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#8]
When you are joining the game, the banner would pause and it would look funny. So it might be a good idea to keep on playing while joining.

[Screen recording 2022-10-17 09.21.00.webm](https://user-images.githubusercontent.com/58097612/196187899-32b2df43-1283-4a21-88c8-2d893070028c.webm)

#6 is in action here to, I tried clearing local data, cookies, cache, still no dice.

**Comment by eliasku** [comment]
I can't keep splash screen state while loading/creating new state, so I just try to simulate and leave animated logo and previous map drawing
