### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by 3kh0** [eliasku/13#85]
![image](https://user-images.githubusercontent.com/58097612/208718976-3eb1633d-5c24-4040-a0fc-903682f81366.png)

I clone it, when installing packages from npm it worked just fine

**Comment by eliasku** [comment]
@3kh0 I moved `tools/` to `packages/tools/`, seems like your package.json is out of date, current command is `"build": "ts-node --esm --swc packages/tools/build.ts"`, but I notice your version runs old `ts-node --esm --swc tools/build.ts`

**Comment by 3kh0** [comment]
ah i see, make sure you update the README.md

**Comment by 3kh0** [comment]
Ah it was not that, my version of node.js was v12, once I updated, that fixed it

**Comment by eliasku** [comment]
@3kh0 I will update requirements, because right now I personally do checks on NodeJS v18
